:modes:
  - :default: 
    - :intro:  
    - :demo:
        :level_file: one.yml
    - :demo:
        :level_file: two.yml
    - :demo:
        :level_file: three.yml
    - :demo:
        :level_file: dont_lose_anyone.yml
    - :demo:
        :level_file: feed_the_giant.yml
    - :demo:
        :level_file: four.yml
    - :credits:
